name: test

on:
  workflow_dispatch:
    inputs:
      test:
        type: asdf
        default: "0"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: printf "%s\n" "${{ toJSON(github) }}" | jq .
