name: test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        foo:
          - bar
          - baz
    runs-on: ubuntu-latest
    steps:
    - name: "Test"
      run: echo ${{ matrix.foo }}
