name: test

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: gh auth status && gh pr -R inahga/inahgabag review --approve 4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
