name: test

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs: ${{ steps.test.outputs }}
    steps:
    - id: test
      uses: actions/github-script@v6
      with:
        file: foo
        test: bar
        script: |
          const file = core.getInput('file', { required: true });
          const test = core.getInput('test', { required: true });

          console.log(file)
          console.log(test)
