name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.ref }}
    - name: Check if running on a valid branch
      if: github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/heads/release/')
      run: |
        echo "You shall not pass"
        exit 1

