name: test

on:
  pull_request:
  workflow_dispatch:
    inputs:
      test:
        description: "revert last migration"
        default: false
        required: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check that existing migrations have not changed
      if: github.event_name == "pull_request"
      env:
        BASE_SHA: "${{ github.event.pull_request.base.sha }}"
      run: echo $BASE_SHA
