name: test

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      outputs: ${{ steps.step1.outputs }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
