name: test

on:
  pull_request:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: get parameters
        run: |
          RUN_JOB_2=true
          RUN_JOB_3=
          echo "run_job_2=$RUN_JOB_2" >>$GITHUB_OUTPUT
          echo "run_job_3=$RUN_JOB_3" >>$GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    # if: ${{ needs.job1.outputs.run_job_2 == 'true' }}
    steps:
      - run: echo job2 was run
      - run: |
          RESULTS=$(echo "results of job2" | base64)
          echo "results=$RESULTS" >>$GITHUB_OUTPUT

  job3:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.run_job_3 == 'true' }}
    steps:
      - run: echo job3 was run
      - run: |
          RESULTS=$(echo "results of job3" | base64)
          printf "results=%s\n" "$RESULTS" >>$GITHUB_OUTPUT

  job4:
    runs-on: ubuntu-latest
    needs:
      - job2
      - job3
    steps:
      - env:
          JOB2_RESULTS: ${{ needs.job2.outputs.results }}
          JOB3_RESULTS: ${{ needs.job3.outputs.results }}
        run: |
          echo "Job 2:"
          printf "%s\n" "$JOB2_RESULTS" | base64 -d
          echo "Job 3:"
          printf "%s\n" "$JOB3_RESULTS" | base64 -d
