name: test

on:
  workflow_dispatch:
    inputs:
      test:
        type: asdf
        default: "0"
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
