name: test

on:
  pull_request:
  workflow_dispatch:
    inputs:
      test:
        default: false
        required: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(inputs.TEST) }}
